name: Update

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm i
    - run: |
        node parser.js > list.new.txt
        if [ "$(diff list.txt list.new.txt)" ]; then
          echo "List files differ, a new pull request will be created"
          mv list.new.txt list.txt
          echo "CREATE_PULL_REQUEST=1" >> $GITHUB_ENV
          echo "NOW=$(date +'%Y-%m-%d_%H.%M.%S')" >> $GITHUB_ENV
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      if: $${{ env.CREATE_PULL_REQUEST == '1' }}
      with:
        title: Update domain list
        branch: ${{ env.NOW }}-update-domain-names
